export const rotatingStatuses = [
  "🤖 Trying to explain Discord to Discord",
  "☕ Powered by caffeine and bugs",
  "🐛 Fixing bugs I definitely didn’t create",
  "💀 Running on 2% sanity",
  "📺 Watching logs like Netflix",
  "🗑️ Deleting tickets by accident (again)",
  "🔄 Surviving another restart",
  "💻 Bot.exe has stopped responding… just kidding",
  "📊 Counting how many times I crashed today",
  "🕒 I was coded at 3AM, don’t trust me",
  "🤯 Making devs question their life choices",
  "📖 Reading error logs like bedtime stories",
  "🧠 Stealing RAM respectfully",
  "🫠 Thinking… therefore crashing",
  "🛡️ Still better than human moderation",
  "🔥 Helping servers fall apart professionally",
  "😐 Currently pretending to be useful",
  "🐞 if (working) return false;",
  "🧾 console.log('why am I here')",
  "📩 Waiting for /help to be used",
  "⚡ Auto-replying to chaos",
  "☁️ Running on hopes and Node.js",
  "🔥 This is fine",
  "🤖 Beep boop chaos engine online",
  "📉 Discord’s unpaid intern",
  "🐛 Making bugs faster than fixes",
  "🎭 Probably broken, but stylish",
  "🐜 Your friendly neighborhood bug magnet",
  "❌ Error 404: stability not found",
  "🍳 I eat stack traces for breakfast",
  "⏳ Still loading… since 2020",
  "💥 Spawning new errors every second",
  "😵 Powered by anxiety and JavaScript",
  "🤞 I promise I work… sometimes",
  "📡 Ask me again later",
  "🧵 No thoughts, just async",
  "👀 Why are you reading this?",
  "🧾 I blame Discord API",
  "💣 If I crash, I didn’t",
  "🌍 Deploying chaos worldwide",
  "📶 One ping away from disaster",
  "🪤 Help I’m stuck in a loop",
  "🚫 Don’t touch production",
  "🔥 Everything is fine (lie)",
  "📦 Running better in theory",
  "😖 I debug therefore I suffer",
  "⌛ Still compiling jokes…",
  "🧠 This bot needs therapy",
  "💀 System.out.println('pain')",
  "❓ 404: humor not found",
  "🧩 Half bot, half mistakes",
  "☕ Powered by coffee overflow",
  "📊 Why are tickets multiplying?",
  "👋 I exist because you clicked start",
  "⏱️ Awaiting inevitable crash",
  "💾 Loading personality module… failed",
  "😴 Too lazy to fix myself",
  "🎬 I came, I saw, I errored",
  "🧙 Server whisperer (bad at it)",
  "📂 Living rent-free in your logs",
  "📡 I speak fluent JSON errors",
  "📶 My uptime is a suggestion",
  "🧪 I was not tested in production",
  "☎️ Help desk’s worst nightmare",
  "🧬 Built different (broken)",
  "⚙️ I automate chaos efficiently",
  "📈 Still better than v1",
  "🔁 Ask again after reboot",
  "😵 Why is CPU crying?",
  "📉 Stack overflow speedrun any%",
  "🎲 I run on vibes only",
  "🧨 Discord but unstable",
  "🤔 System: confused",
  "🛠️ I make moderation questionable",
  "🤖 Just a bot doing bot things",
  "🔄 Probably updating… forever",
  "🏠 I live inside your server now",
  "✍️ My code writes itself (badly)",
  "🚷 Please don’t inspect me",
  "💣 I fear no bug… except all of them",
  "🚀 Deploy now, cry later",
  "🔧 I fix things by breaking more",
  "🧍 Still not a human (I checked)",
  "🩺 Running diagnostics: nope",
  "📊 I am 99% console logs",
  "🆘 This status is a cry for help",
  "📍 If lost, return to dev",
  "🎯 I do things… sometimes correctly",
  "🌪️ Chaos is my default state",
  "💡 I was built on optimism",
  "🙃 Currently ignoring errors",
  "📣 Why are you pinging me?",
  "⚡ I respond faster than I think",
  "🤨 Botting responsibly (questionable)",
  "📛 I am the error message",
  "⏳ Still loading jokes… please wait",
  "📉 I make Discord slightly worse",
  "🧾 Everything works until it doesn’t",
  "📜 I am legally a feature",
  "🔥 Powered by stack traces and dreams"
];
